import "./globals.css";
import Navbar from "./components/navbar";
import { AuthProvider } from "../context/authContext";
import { Toaster } from "react-hot-toast";
import { Montserrat } from "next/font/google";
import ReduxProvider from "./redux/reduxProvider";

const montserrat = Montserrat({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <AuthProvider>
          {/* <Loading/> */}
          <Navbar />
          <Toaster position="top-right" reverseOrder={false} />
          {/* <Provider store={store}>{children}</Provider> */}
          <ReduxProvider>
          {children}
          </ReduxProvider>
          {/* </Suspense> */}
        </AuthProvider>
      </body>
    </html>
  );
}
